FROM node:16-alpine

# create destination directory
RUN mkdir -p /usr/src/client
WORKDIR /usr/src/client

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git

# copy the app, note .dockerignore
ADD . /usr/src/client
RUN yarn install
RUN yarn build

# Expose the app
EXPOSE 8080

# Run the app
CMD ["node", "server.js"]
