name: Client CI

on: [push]

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn

      - name: Linting
        run: yarn lint
      
      - name: Build
        run: yarn build
