name: Server CI

on: [push]

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: bun install

      - name: Linting
        run: bun lint

      - name: Tests
        run: bun test
